"""change blob type

Revision ID: 06c8500068ae
Revises: 16a4e6274ac0
Create Date: 2023-10-08 12:03:51.597608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c8500068ae'
down_revision: Union[str, None] = '16a4e6274ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'raw_data',
               existing_type=sa.BLOB(),
               type_=sa.LargeBinary(length=(2**32)-1),
               existing_nullable=False)
    op.alter_column('image', 'treated_data',
               existing_type=sa.BLOB(),
               type_=sa.LargeBinary(length=(2**32)-1),
               existing_nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'raw_data',
               existing_type=sa.LargeBinary(length=(2**32)-1),
               type_=sa.BLOB(),
               existing_nullable=False)
    op.alter_column('image', 'treated_data',
               existing_type=sa.LargeBinary(length=(2**32)-1),
               type_=sa.BLOB(),
               existing_nullable=True)
    pass
    # ### end Alembic commands ###
