"""init database

Revision ID: 16a4e6274ac0
Revises: 
Create Date: 2023-10-08 11:37:16.235289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a4e6274ac0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.BLOB(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_ext', sa.String(length=255), nullable=True),
    sa.Column('treated_data', sa.BLOB(), nullable=True),
    sa.Column('charset', sa.String(length=255), nullable=True),
    sa.Column('insert_date', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
