"""add prontuario

Revision ID: 1866d28fe1c8
Revises: 2e4177cab033
Create Date: 2023-10-24 21:09:10.428779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1866d28fe1c8'
down_revision: Union[str, None] = '2e4177cab033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionario', sa.Column('prontuario', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionario', 'prontuario')
    # ### end Alembic commands ###
